name: Build Flutter APK with Flet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.1

      # Step 3: Update and install necessary tools
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo snap install flutter
          sudo apt install -y android-sdk sdkmanager

      # Step 4: Setup Android NDK and accept licenses
      - name: Setup Android SDK
        run: |
          sudo -E sdkmanager --install "ndk;23.1.7779620"
          yes | sudo -E sdkmanager --licenses

      # Step 5: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 6: Build the APK using Flet
      - name: Build APK
        run: |
          flutter config --no-analytics
          flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      # Step 7: Upload APK artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: apk-build-artifact
          path: build/apk
          if-no-files-found: warn
          overwrite: false
