name: Build Android APK with Flet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install Flet
      - name: Install Flet
        run: |
          python -m pip install --upgrade pip
          pip install flet

      # Install Flutter SDK
      - name: Install Flutter SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.13.0-stable.tar.xz
          sudo tar -xf flutter_linux_3.13.0-stable.tar.xz -C /opt
          echo "export PATH=/opt/flutter/bin:$PATH" >> $GITHUB_ENV
          flutter doctor --android-licenses
          flutter doctor

      # Install Android SDK and dependencies
      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      # Build APK using Flet
      - name: Build APK
        run: |
          flutter pub get
          flet build apk

      # Upload APK as artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/apk/release/*.apk
