name: Build Android APK with Flet on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: windows-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python 3.13.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      # Install Flet
      - name: Install Flet
        run: |
          python -m pip install --upgrade pip
          pip install flet

      # Install Flutter using GitHub Action
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # Replace with the required Flutter version

      # Set up Android SDK
      - name: Set up Android SDK
        run: |
          choco install -y openjdk11
          choco install -y android-sdk
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      # Accept Android licenses and check Flutter setup
      - name: Set up Flutter Environment
        run: |
          flutter doctor --android-licenses
          flutter doctor

      # Build APK using Flet
      - name: Build APK
        run: |
          flutter pub get
          flet build apk

      # Upload APK as artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/apk/release/*.apk
