name: Build Android APK with Flet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'  # Ensure compatible Python version

      # Install Flet and dependencies
      - name: Install Flet
        run: |
          python -m pip install --upgrade pip
          pip install flet

      # Set up Java environment for Android build tools
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'  # Required for Android tools

      # Install Android SDK
      - name: Install Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: default
          arch: x86_64
          channel: stable

      # Build APK
      - name: Build APK
        run: |
          flet build apk

      # Upload APK as artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/apk/release/*.apk
